---
- name: Ensure apache is installed and started
  hosts: web
  become: yes
  tasks:
  - name: Ensure httpd package is present
    yum:
      name: httpd
      state: present

  - name: Ensure latest index.html file is present
    copy:
      src: files/index.html
      dest: /var/www/html/

  - name: Ensure httpd is started
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Enable access to port 80
    firewalld:
      service: http
      permanent: true
      state: enabled
    changed_when: true
    notify: firewalld-reload

  handlers:
  - name: firewalld-reload
    command: firewall-cmd --reload
